### PR TITLE
Add Slovenian (sl) l10n

### PR DESCRIPTION
**Pull request by filmsi**
Courtesy of Slovenian GNOME l10n team.

Thank you.

BTW, adding files via Gnome Damned Lies is not working for Cassette, upon uploading the po file it responds with the following error (this means Cassette might not end localized into many languages):
 »[Errno 128] Command: ‘['git', 'push', 'origin', 'main']’, Error: Warning: Permanently added 'github.com' (ED25519) to the list of known hosts. ERROR: Permission to Rirusha/Cassette.git denied to gnomeinfra-github. fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. «.

### CODE REVIEW

**Comment by fiersik** [comment]
@filmsi what is strange about banning direct writes to the repository? All changes are only made through pr

**Comment by Rirusha** [comment]
The problem is known. There was some confusion in providing access to the repository.

https://gitlab.gnome.org/Teams/Translation/Coordination/-/issues/164#note_2213268

**Comment by Rirusha** [comment]
Thanks for the translation, but I'm sorry. I have agreed that the transfer will not be accepted through MR/PR in the issue mentioned above. Please add the translation as soon as GNOME Infrastructure accepts the invitation to write to this repository.

**Comment by filmsi** [comment]
So this is how you support l10n?

**Comment by Rirusha** [comment]
I'm not sure what the technical consequences might be; there must be a reason why they have this rule.

Though I realized I made the wrong decision yesterday, it’s not wise to rely on something that isn't working yet.

I'll reopen the PR. Thanks for the translation!

**Pull request merged**
